# Generated by Django 6.0.5 on 2026-06-08 11:09
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # This must match the name of the previous migration file in your folder
        ('quiz', '0001_initial'),
    ]

    operations = [
        # 1. Force remove the old unique constraint from the index_number column
        migrations.AlterField(
            model_name='allowedstudent',
            name='index_number',
            field=models.CharField(max_length=20),
        ),
        # 2. Bind the new unique constraint across both index_number and course together
        migrations.AddConstraint(
            model_name='allowedstudent',
            constraint=models.UniqueConstraint(fields=['index_number', 'course'], name='unique_student_per_course'),
        ),
    ]

