# Generated by Django 6.0.5 on 2026-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_name',
            field=models.CharField(default='End of Semester Exam', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
