# Generated by Django 6.0.5 on 2026-06-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20260608_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz / Continuous Assessment'), ('ASSIGNMENT', 'Take-Home Assignment'), ('MIDSEM', 'Mid-Semester Examination'), ('PROJECT', 'Project Submission'), ('FINAL', 'End of Semester Exam')], default='QUIZ', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_name',
            field=models.CharField(help_text='e.g., Quiz 1, Midsem, Project Phase 1', max_length=200),
        ),
    ]
