# Generated by Django 6.0.5 on 2026-05-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_duration_minutes_course_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='submitted_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
