# Generated by Django 6.0.5 on 2026-06-11 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_course_assessment_type_alter_course_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_name',
            field=models.CharField(help_text='e.g., Quiz 1, Midsem', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=7.332, max_digits=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-2.312, max_digits=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='radius_meters',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
