# Generated by Django 6.0.5 on 2026-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_course_end_time_alter_course_exam_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='radius_meters',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='submitted_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
