# Generated by Django 6.0.5 on 2026-06-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_course_end_time_course_start_time_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
