# Generated by Django 6.0.5 on 2026-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_course_radius_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], default='QUIZ', max_length=10),
        ),
    ]
