# Generated by Django 6.0.5 on 2026-06-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FITB', 'Fill in the Blank'), ('THEORY', 'Written Essay')], default='MCQ', max_length=200),
        ),
    ]
