# Generated by Django 6.0.5 on 2026-06-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_studentsubmission_assignment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='assignment_file',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
