# Generated by Django 6.0.5 on 2026-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_studentsubmission_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='index_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together={('index_number', 'course')},
        ),
    ]
