# Generated by Django 6.0.5 on 2026-06-15 22:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_studentsubmission_index_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='file_name',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='assignment'),
        ),
    ]
