# Generated by Django 5.1.4 on 2026-06-15 23:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_studentsubmission_file_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='assignment'),
            preserve_default=False,
        ),
    ]
